# Generated by Django 4.2.2 on 2023-06-19 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Accounts", "0002_message_media_friends"),
    ]

    operations = [
        migrations.AddField(
            model_name="user_profile",
            name="profile_name",
            field=models.CharField(default="N", max_length=20),
        ),
        migrations.AlterField(
            model_name="user_profile",
            name="profile_pic",
            field=models.ImageField(upload_to="profiles/"),
        ),
    ]
