# Generated by Django 4.2.2 on 2023-06-19 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Accounts", "0003_user_profile_profile_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user_profile",
            name="profile_name",
            field=models.CharField(max_length=20),
        ),
    ]
