# Generated by Django 4.2.2 on 2023-06-19 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Accounts", "0004_alter_user_profile_profile_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user_profile",
            name="profile_pic",
            field=models.ImageField(null=True, upload_to="profiles/"),
        ),
    ]
