# Generated by Django 4.2.2 on 2023-06-19 11:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("Accounts", "0006_remove_user_profile_profile_pic_profile_pic"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile_pic",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user_pic",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
