# Generated by Django 4.2.2 on 2023-06-21 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Accounts", "0007_alter_profile_pic_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="friends",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="friends",
            name="frnd_requests",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="friends",
            name="is_accepted",
            field=models.BooleanField(default=False),
        ),
    ]
